In [ ]:
import pandas as pd
pb_10y = pd.read_csv('C:/Users/DJA/Downloads/데이터/정제자료/인구관련/birth_monthly08_17_u8.csv')


pb_10y.head()

,지역번호,지역,0801,0802,0803,0804,0805,0806,0807,0808,...,1703,1704,1705,1706,1707,1708,1709,1710,1711,1712
0,1,전국,41182.0,41537.0,40749.0,39625.0,38863.0,35929.0,38009.0,36235.0,...,33836.0,29242.0,33174.0,29911.0,28843.0,31291.0,30089.0,28215.0,28548.0,26615.0
1,1100000000,서울특별시,8005.0,8618.0,8338.0,8137.0,8051.0,7398.0,7823.0,7394.0,...,6283.0,5382.0,6041.0,5514.0,5218.0,5609.0,5553.0,5100.0,5149.0,4987.0
2,1111000000,서울특별시 종로구,109.0,118.0,95.0,82.0,82.0,84.0,101.0,87.0,...,54.0,44.0,63.0,62.0,60.0,57.0,62.0,56.0,48.0,61.0
3,1111051500,서울특별시 종로구 청운효자동,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.0,7.0,3.0,7.0,9.0,6.0,5.0,8.0,9.0,6.0
4,1111053000,서울특별시 종로구 사직동,2.0,9.0,2.0,5.0,6.0,0.0,11.0,6.0,...,2.0,4.0,4.0,5.0,5.0,2.0,5.0,2.0,2.0,5.0

In [ ]:
rank1 = 4773035000
r_rgl = [4889031000,4888040000,2826057500,4775035000,4772034000,4773039000,4888025000,2826059000,4772031000,4773033000
        ,4775000000,4776031000,2826054400,4677042000,4773000000,2826056000,4773036000,2826054200,4673035000]
# r_rgl = ['4889031000','4888040000','2826057500','4775035000','4772034000','4773039000','4888025000','2826059000','4772031000']

# 1위 '4773035000' 경상북도 의성군 춘산면
rank1_20 = pb_10y[pb_10y['지역번호'] == rank1]
rank1_20 = rank1_20.T
rank1_20 = rank1_20.drop(rank1_20.index[[0]])

rank1_20.head()

              3341
지역    경상북도 의성군 춘산면
0801             0
0802             2
0803             2
0804             0

In [29]:
# t = pd.concat([rank11,rank12],axis=1)
# t

for i in r_rgl:
    rank = pb_10y[pb_10y['지역번호'] == i]
    rank = rank.T
    rank = rank.drop(rank.index[[0]])
    rank1_20 = pd.concat([rank1_20,rank],axis=1)

rank1_20

,3341,3787,3783,952,3360,3331,3345,3773,954,3328,...,3339,3354,3365,948,2914,3335,950,3342,946,2895
지역,경상북도 의성군 춘산면,경상남도 합천군 봉산면,경상남도 거창군 가조면,인천광역시 서구 신현원창동,경상북도 청송군 안덕면,경상북도 군위군 우보면,경상북도 의성군 비안면,경상남도 거창군 거창읍,인천광역시 서구 가좌2동,경상북도 군위군 소보면,...,경상북도 의성군 옥산면,경상북도 청송군,경상북도 영양군 입암면,인천광역시 서구 가정3동,전라남도 고흥군 두원면,경상북도 의성군,인천광역시 서구 석남2동,경상북도 의성군 가음면,인천광역시 서구 가정1동,전라남도 구례군 광의면
0801,0,1,6,15,1,0,1,31,19,1,...,2,12,0,10,3,31,14,0,17,1
0802,2,2,1,12,1,1,1,22,20,2,...,2,16,0,9,1,26,11,0,17,0
0803,2,3,1,13,1,0,0,27,24,5,...,0,10,2,6,1,39,11,0,15,3
0804,0,1,3,12,1,1,0,32,21,2,...,1,22,1,9,2,25,10,1,21,2
0805,1,1,0,14,1,2,0,21,21,0,...,0,15,0,7,2,33,10,0,17,0
0806,2,1,1,9,1,0,0,25,25,0,...,0,11,0,9,1,23,18,0,19,0
0807,0,1,0,6,1,1,0,23,12,0,...,0,8,1,5,0,18,11,0,13,2
0808,0,1,2,12,0,0,2,24,20,1,...,3,11,2,9,2,20,14,0,7,1
0809,2,1,1,12,0,2,0,28,23,2,...,1,10,1,13,0,33,5,0,13,2
0810,0,1,3,8,3,0,1,16,18,0,...,1,19,2,8,1,42,15,1,10,1
0811,0,0,1,10,1,1,0,32,23,1,...,1,18,1,4,0,28,15,0,9,1
0812,0,2,2,7,1,3,3,30,31,3,...,0,14,1,13,0,23,12,0,10,3
0901,1,1,4,15,1,2,3,28,24,0,...,0,16,3,10,1,23,8,0,8,0
0902,2,0,3,12,1,1,0,37,23,3,...,0,8,2,14,2,32,12,1,14,1
0903,0,0,0,7,1,3,1,39,23,2,...,0,15,0,6,0,18,17,0,4,0
0904,0,0,2,10,2,0,2,30,18,0,...,1,25,0,13,1,29,15,1,13,0
0905,0,1,0,9,1,0,1,33,22,2,...,0,7,0,8,1,26,15,0,4,0
0906,0,1,0,6,0,1,3,26,12,2,...,3,8,1,9,0,32,12,1,8,2
0907,1,1,2,8,1,1,1,25,16,1,...,1,9,0,10,1,24,10,1,6,3
0908,1,1,0,17,2,0,0,21,23,0,...,0,15,2,9,4,29,16,0,7,0
0909,0,2,2,6,2,0,0,20,17,1,...,0,12,0,8,0,29,17,1,9,0
0910,0,1,2,9,0,0,0,26,12,2,...,1,12,0,6,4,20,14,0,5,1
0911,2,0,0,12,1,1,0,20,16,0,...,0,6,2,6,4,22,16,0,10,4
0912,0,3,0,10,0,1,1,23,27,0,...,0,7,1,13,4,21,8,1,7,1
1001,3,0,0,17,0,0,1,26,22,0,...,1,12,2,6,2,30,9,0,11,2
1002,1,2,1,16,0,3,0,19,33,0,...,1,11,0,4,2,25,16,2,11,2
1003,0,0,2,14,2,3,0,33,15,0,...,0,14,1,8,1,28,17,1,12,1
1004,1,1,1,23,1,1,1,29,17,2,...,2,6,1,8,2,22,17,0,7,7
1005,0,1,3,14,1,1,2,24,22,1,...,1,10,1,10,1,26,7,1,10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1507,0,1,0,17,0,0,0,21,14,0,...,1,12,1,7,1,26,8,0,7,1
1508,1,0,0,23,0,1,0,18,11,0,...,0,10,2,8,0,19,7,0,6,0
1509,0,1,0,15,2,0,0,20,11,0,...,1,14,1,5,1,12,10,0,7,0
1510,1,0,1,17,1,1,2,26,18,1,...,0,13,0,5,0,30,7,1,10,2
1511,0,0,1,11,0,0,0,27,13,1,...,1,11,1,4,1,21,8,0,11,2
1512,1,0,1,15,0,0,1,23,10,0,...,0,10,2,3,0,19,8,0,14,0
1601,0,1,0,12,4,0,2,21,15,0,...,1,14,2,7,0,20,13,0,13,0
1602,1,0,1,19,0,1,2,30,16,0,...,0,6,0,11,0,21,12,0,15,0
1603,0,0,2,23,2,0,2,25,15,0,...,2,18,1,3,1,26,11,0,16,1
1604,0,0,0,18,0,0,2,28,16,0,...,3,6,0,6,2,25,2,0,16,0
1605,0,0,0,16,2,1,0,30,11,2,...,0,12,0,6,1,21,5,1,13,1
1606,2,1,0,14,0,0,2,26,14,0,...,0,10,1,7,1,21,10,1,5,1
1607,0,0,2,18,1,2,1,23,15,1,...,0,10,0,3,2,16,9,0,13,0
1608,0,1,0,14,0,1,2,23,16,0,...,0,12,0,8,1,30,8,1,13,2
1609,0,1,1,16,0,1,1,23,13,2,...,2,6,1,6,1,23,10,1,13,0
1610,0,0,1,18,1,0,4,31,15,1,...,0,12,2,9,2,17,7,0,11,1
1611,1,0,0,18,1,1,0,21,20,0,...,0,10,0,4,0,27,8,0,9,0
1612,0,1,3,17,1,0,1,21,6,0,...,1,12,0,6,0,23,10,0,11,1
1701,0,0,0,12,0,1,0,22,10,1,...,0,4,2,4,0,14,3,0,12,0
1702,1,0,0,20,3,2,0,24,17,1,...,0,16,0,2,1,22,8,0,13,1
1703,1,0,0,18,2,1,0,31,17,1,...,1,15,1,6,0,28,11,0,13,0
1704,0,1,0,10,1,0,3,14,8,0,...,0,12,2,5,1,13,3,0,13,1
1705,0,0,0,18,1,0,1,28,10,3,...,2,14,2,6,0,17,8,1,10,0
1706,1,0,0,7,0,0,1,20,9,1,...,0,8,5,5,0,20,5,0,10,1
1707,0,0,0,10,0,1,1,22,11,0,...,2,8,1,5,1,21,5,0,14,0
1708,0,0,0,14,0,0,0,28,14,1,...,0,11,1,6,0,17,5,0,13,0
1709,0,0,3,9,0,1,0,14,8,1,...,1,8,1,1,0,24,7,0,16,1
1710,0,0,1,19,0,0,0,15,6,0,...,1,11,1,6,1,13,8,0,13,1
1711,2,0,2,8,1,1,2,22,7,0,...,0,9,0,4,1,17,6,0,13,0
1712,0,1,0,16,0,0,1,19,6,0,...,1,10,0,6,0,15,6,0,5,0

In [30]:
rank1_20.to_csv("brith_rank1_20.csv",mode='w')