In [57]:
import pandas as pd
pr_08_17 = pd.read_csv('C:/Users/DJA/Downloads/데이터/정제자료/인구관련/pop_monthly_rate08_17_u8.csv')

# pr_08_17.dtypes
pr_08_17[['지역번호']] = pr_08_17[['지역번호']].astype(str)
# pr_08_17.dtypes

tmp = pr_08_17[pr_08_17['지역번호'].str[4:]== '000000']
tmp.head()

,지역번호,지역,0801,0802,0803,0804,0805,0806,0807,0808,...,1703,1704,1705,1706,1707,1708,1709,1710,1711,1712
0,1100000000,서울특별시,4.257664,4.225334,4.189716,4.169195,4.151027,4.136442,4.117900,4.094905,...,2.325830,2.317569,2.303019,2.295035,2.284388,2.274636,2.263960,2.252767,2.242796,2.228718
1,1111000000,서울특별시 종로구,2.878918,2.873993,2.850645,2.851153,2.847277,2.853872,2.853100,2.844921,...,1.760279,1.760016,1.751165,1.750088,1.745725,1.745106,1.743528,1.738360,1.737689,1.730849
22,1114000000,서울특별시 중구,3.057053,3.027444,3.012814,2.996634,2.986344,2.984163,2.980442,2.971326,...,1.238390,1.234837,1.223421,1.236025,1.230530,1.239567,1.220339,1.229329,1.201248,1.196262
38,1117000000,서울특별시 용산구,3.330504,3.304664,3.289517,3.280052,3.274397,3.277130,3.284478,3.264230,...,1.422408,1.408022,1.391126,1.359513,1.344572,1.329752,1.317599,1.304698,1.317631,1.307383
55,1120000000,서울특별시 성동구,4.081358,4.044800,4.007542,3.984387,3.969854,3.955764,3.933835,3.909984,...,2.332423,2.329398,2.328196,2.321763,2.324977,2.311976,2.282979,2.274896,2.267815,2.257549

In [58]:
tmp.to_csv("pop_city_monthly_rate08_17_u8.csv")